### ISSUE TITLE
Kube hunter running as Job with args --report=json not working

### ISSUE THREAD

**Issue by jvaibhav123** [aquasecurity/kube-hunter#109]
Dear Team,

I was trying to run the kube hunter job in k8s with option   
        command: ["python", "kube-hunter.py"]
        args: ["--internal","--report=json"]
However the logs are not coming in json format. I would like to send the logs to elastic search and further integrate with monitoring system in order to generate alerts.

I am not sure if i am doing something wrong while specifying the arguments or is it a bug.
Could you please help me out here.
Thanks in advance.

**Comment by aakarshit-batchu** [comment]
Hi Team,

I am also facing same issue exactly as @jvaibhav123 has specified. Neither the json, nor yaml types are working for the report.
Can you kindly help us with that?
Thanks in advance.

**Comment by yoavrotems** [comment]
Hey when I run the same command as you i get the output in json, could you maybe add the output you get?

**Comment by jvaibhav123** [comment]
@yoavrotems I used the job.yaml provided in github with option in args like args: ["--internal","--report=json"]

apiVersion: batch/v1
kind: Job
metadata:
  name: kube-hunter
spec:
  template:
    spec:
      containers:
      - name: kube-hunter
        image: aquasec/kube-hunter 
        command: ["python", "kube-hunter.py"]
        args: ["--internal" ,"report=json"]
      restartPolicy: Never
  backoffLimit: 4

**Comment by jvaibhav123** [comment]
@yoavrotems Just wanted to check if get chance to look at above issue?

**Comment by yoavrotems** [comment]
Yes i'm on it, didnt figure it out yet

**Comment by lizrice** [comment]
I have the beginnings of a theory... Can you check whether you have a `src/modules/report/json.pyc`  file? There was a brief period where `json.py` existed, but it messes up the import for the standard json library and the file was renamed to `json_reporter.py`. 

Even if this turns out to be a red herring, I think this and #108 are the same thing.

**Comment by jvaibhav123** [comment]
Just wanted to check if you get chance to look at the issue.

**Comment by jvaibhav123** [comment]
Just wanted to check if you get chance to look at the issue?

**Comment by lizrice** [comment]
@jvaibhav123 did you get a chance to see if there’s a json.pyc file in your system? See my last comment

**Comment by lizrice** [comment]
Closing as stale and also duplicate of #108
