### ISSUE TITLE
Evidence field truncated in the Vulnerability table

### ISSUE THREAD

**Issue by aakarshit-batchu** [aquasecurity/kube-hunter#111]
Hi Team,

The report generated in the logs has a vulnerability table. The Evidence field in the table is truncated, and so we are not able to find the root cause of that vulnerability.

_Below is the image and report file of the issue:_
[kube-hunter-uklab-18-report.log](https://github.com/aquasecurity/kube-hunter/files/3013130/kube-hunter-uklab-18-report.log)

![truncated](https://user-images.githubusercontent.com/27916328/55076593-dab65680-50bb-11e9-87d6-69ffd590ec63.PNG)

`
Vulnerabilities
+--------------------+----------------------+----------------------+----------------------+----------------------+
| LOCATION           | CATEGORY             | VULNERABILITY        | DESCRIPTION          | EVIDENCE             |
+--------------------+----------------------+----------------------+----------------------+----------------------+
| 10.233.64.1:6443   | Remote Code          | Access to server API |  Accessing the       | {"kind":"APIVersions |
|                    | Execution            |                      | server API within a  | ","versions":["v1"], |
|                    |                      |                      | compromised pod      | ...                  |
|                    |                      |                      | would help an        |                      |
|                    |                      |                      | attacker gain full   |                      |
|                    |                      |                      | control over the     |                      |
|                    |                      |                      | cluster              |                      |
+--------------------+----------------------+----------------------+----------------------+----------------------+
| 10.233.64.1:6443   | Information          | Listing pods list    |  Accessing the pods  | [{'namespace':       |
|                    | Disclosure           | under default        | list under default   | 'default', 'name':   |
|                    |                      | namespace            | namespace might give | 'glust...            |
|                    |                      |                      | an attacker valuable |                      |
|                    |                      |                      |      information to  |                      |
|                    |                      |                      | harm the cluster     |                      |
+--------------------+----------------------+----------------------+----------------------+----------------------+
| 10.233.64.1:6443   | Information          | Listing all roles    |  Accessing all of    | ['prometheus-k8s',   |
|                    | Disclosure           |                      | the roles might give | 'kubeadm:bootstrap-  |
|                    |                      |                      | an attacker valuable | si...                |
|                    |                      |                      | information          |                      |
+--------------------+----------------------+----------------------+----------------------+----------------------+
| 10.233.64.1:6443   | Information          | Listing all          |  Accessing all of    | ['a', 'abc', 'alpha- |
|                    | Disclosure           | namespaces           | the namespaces might | customer', 'b',      |
|                    |                      |                      | give an attacker     | 'c',...              |
|                    |                      |                      | valuable information |                      |
+--------------------+----------------------+----------------------+----------------------+----------------------+

`

Kindly help us with this issue.
Thanks in advance

**Comment by yoavrotems** [comment]
Hey, you can use the --report=json flag and get the full value there, for example:
<img width="534" alt="Capture" src="https://user-images.githubusercontent.com/12915002/55086745-958d2700-50b1-11e9-972f-f0ea971f1225.PNG">
As you can see the evidence part ("Pod: kube...") is truncated.
But in the json output:

> "category":"Access Risk",
> "vulnerability":"Privileged Container",
> "evidence":"pod: kube-proxy-7hnks, container: kube-proxy",
> "location":"192.168.99.100:10255",
> "description":"A Privileged container exist on a node. could expose the node/cluster to unwanted root operations"

The json field evidence is full.

**Comment by aakarshit-batchu** [comment]
Hi @yoavrotems ,

I ran the kube-hunter using the pod method. Below is the yaml file that i am using:

`
apiVersion: batch/v1
kind: Job
metadata:
  name: kube-hunter
spec:
  template:
    spec:
      containers:
      - name: kube-hunter
        image: aquasec/kube-hunter
        command: ["python", "kube-hunter.py"]
        args: ["--pod","--cidr=10.233.64.0/18","--report=json"]
      restartPolicy: Never
  backoffLimit: 4

`

When i run this job, i am getting a truncated output only as i have mentioned above.
Kindly let me know, if i have to make any changes to that file to get the desired output.

Thanks in advance.

**Comment by yoavrotems** [comment]
Are you using our latest kube-hunter version?

**Comment by aakarshit-batchu** [comment]
yes @yoavrotems , I am running a kubernetes job with image aquasec/kube-hunter, so it should be pulling latest image from docker hub.

**Comment by aakarshit-batchu** [comment]
@yoavrotems --report=yaml is working, but --report=json is not working with that image.

**Comment by danielsagi** [comment]
@aakarshit-batchu aquasec/kube-hunter image has been updated, please check again and let me know if your problem consist.

**Comment by lizrice** [comment]
I think we could extend the length of what is shown in the Evidence field, as it's quite a lot shorter than the descriptions, so there is space for more

**Comment by iYehuda** [comment]
Can we close this issue? @aakarshit-batchu @lizrice

**Comment by lizrice** [comment]
@yoavrotems please could you run and grab a screenshot of how much information is now shown in the Evidence output? It would make sense for it to be a similar length to Description

**Comment by reegnz** [comment]
It seems to me that the evidence output is coming directly from python docstrings, and don't have an upper limit defined.
Just skimming through the Events, it seems to me that several strings go beyond 100 characters, so I'd say increasing it to ~100 would be a good first approximation.

**Comment by danielsagi** [comment]
@reegnz actually evidence output does not come from docstrings, it can come from all sorts of IO operations, depending on the hunter that finds it. but It might be good to enlarge the limit
