### ISSUE TITLE
Automated image build is not working

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/kube-hunter#112]
The job that builds an image and pushes it to Docker Hub is currently failing (due to a high severity vulnerability in one of the dependencies)

**Comment by lizrice** [comment]
This is the issue about the vulnerability: https://github.com/boto/botocore/issues/1703

**Comment by lizrice** [comment]
@yoavrotems do we use this extensively? I'm wondering if it's possible to remove the dependency - would we have to lose some functionality to do that?

**Comment by yoavrotems** [comment]
We don't use it, it just comes with the botocore

**Comment by danielsagi** [comment]
this was fixed, the image is now updating
