### ISSUE TITLE
Report output to a file

### ISSUE THREAD

**Issue by Richahasija** [aquasecurity/kube-hunter#113]
How can i log output of command ./kube-hunter.py --remote some.node.com to a file?

**Comment by jgsqware** [comment]
This should work if you're on linux or mac

```
./kube-hunter.py --remote some.node.com > my-report.txt
```

**Comment by Richahasija** [comment]
Thanks Julien. I am using Linux but apparently this is not working.. Any other recommendations?

**Comment by danielsagi** [comment]
@Richahasija to redirect output to a file, you can run:
`
./kube-hunter.py --remote some.node.com 2> my-report.txt
`
logging happens on stderr, this is why you should use 2>
