### ISSUE TITLE
Hunter statistics look misleading

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/kube-hunter#120]
What do the Hunter event counts mean to a user? For example, a non-zero count against Certificate Email Hunting doesn't mean that any email addresses have been found in certificates, just that the hunter was triggered... Please can you explain the intention here @nshauli? 

cc @jerbia

**Comment by iYehuda** [comment]
Do you have an example output?
The event counter should count only subclasses of `Vulnerability` that the hunter has published.
If not so, it is a bug.
