### ISSUE TITLE
ignore hook exceptions in handler

### ISSUE THREAD

**Issue by godaji** [aquasecurity/kube-hunter#124]
Hi, I'm kube-hunter newbie and thank you for this awesome project.

When I execute kube-hunter.py, some hunting is skipped without error message.

```
    # In handler.py (82 line)
    def worker(self):
        while self.running:
            queue_lock.acquire()
            hook = self.get()
            queue_lock.release()

            try:
                hook.execute()
            except Exception as ex:
                **logging.debug(ex)**
            self.task_done()
        logging.debug("closing thread...")
```

I think skipping hunting is important event. Can you give more detail info if hook throw exception? In my case, get_api_server_version_end_point (in cvehunter.py) throw exception and skipped cvehunter.execute.

**Comment by danielsagi** [comment]
see: #137 Thank you!
