### ISSUE TITLE
Unable to scan cluster

### ISSUE THREAD

**Issue by jaxxstorm** [aquasecurity/kube-hunter#16]
My cluster isn't accessible externally, I've tried both the cidr and remote option, but the cluster nevers gets detected. It seems to be because of the use of the azurespeed.com website as part of the scan:

```
Choose one of the options below:
1. Remote scanning      (scans one or more specific IPs or DNS names)
2. Internal scanning    (scans all network interfaces)
3. Network scanning     (scans a given IP range)
Your choice: 3
CIDR (example - 192.168.1.0/24): <ip>/32
Event <class 'src.core.events.types.common.HuntStarted'> got published with <src.core.events.types.common.HuntStarted object at 0x7f9efcab8810>
Event <class 'src.modules.discovery.hosts.HostScanEvent'> got published with <src.modules.discovery.hosts.HostScanEvent object at 0x7f9ed873a550>
~ Started
~ Discovering Open Kubernetes Services...
Starting new HTTP connection (1): www.azurespeed.com:80
http://www.azurespeed.com:80 "GET /api/region?ipOrUrl=<ip> HTTP/1.1" 200 None
Event <class 'src.core.events.types.common.NewHostEvent'> got published with 10.70.0.106
Event <class 'src.core.events.types.common.HuntFinished'> got published with <src.core.events.types.common.HuntFinished object at 0x7f9ed8709410>

Kube Hunter couldn't find any clusters

----------

Event <class 'src.modules.report.default.TablesPrinted'> got published with <src.modules.report.default.TablesPrinted object at 0x7f9f0167fcd0>
Cleaned Queue
```

**Comment by lizrice** [comment]
I don't think it's the azurespeed.com check; that gets ignored if there is no information about that IP address. (This tells us whether the cluster is hosted on Azure; if it is, we have some additional tests to see if it's possible to get to the cloud metadata. One day we should add similar tests for other providers).

Given an IP address, kube-hunter will attempt to open a socket to the following ports: 8001, 10250, 10255, 30000, 443

From the machine you're testing on, try 
```bash
curl <ip address>:<port>
```
for that set of ports, on the IP address of the master node. Can you get anything other than connection refused for any of those ports? If so, kube-hunter should explore further. 

If not, the possibilities include: 
* the IP address is not reachable from where you're running kube-hunter
* the API server is operating on a non-default port (which is interesting, and not something kube-hunter currently tests for, but maybe should have an option to do so)
* something else I haven't thought of!

**Comment by jaxxstorm** [comment]
Ah yes, our API server runs on port 6443:

```
--secure-port=6443
```

This is the kubeadm default as per here: https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/

```
--apiserver-bind-port int32     Default: 6443
```

That's probably the issue

**Comment by jaxxstorm** [comment]
It'd also be worth having some of this issue in the debug logs?

**Comment by lizrice** [comment]
Port 6443 also covered now (and I agree with you on the log info). Does it find the cluster now?

**Comment by jaxxstorm** [comment]
Unfortunately not, it does seem to scan that port now:
```
Event <class 'src.core.events.types.common.OpenPortEvent'> got published with 6443
Event <class 'src.core.events.types.common.HuntFinished'> got published with <src.core.events.types.common.HuntFinished object at 0x7f3770b5f310>

Kube Hunter couldn't find any clusters
```

We firewall off all the other ports, what is the bare minimum for a cluster to be discovered?

**Comment by jaxxstorm** [comment]
Ah, figured it out, PR incoming
