### ISSUE TITLE
Inconsistent or intended behaviour when scanning for writable /var/log hostpath mounts

### ISSUE THREAD

**Issue by pepov** [aquasecurity/kube-hunter#177]
Introduced in https://github.com/aquasecurity/kube-hunter/commit/e5db8b6b282c126af952730a374896b63e48c8fc the `VarLogMountHunter` has a method `has_write_mount_to ` which according to it's name and to the [blog post](https://blog.aquasec.com/kubernetes-security-pod-escape-log-mounts)  should check if there are any `VolumeMounts` in the pod that actually mounts a `hostPath` `Volume` with `/var/log` prefix in readwrite mode.

My question is then why does the hunter not check for the volumemounts but only checks the volume? This check would then be a false positive if there is a readonly volumemount pointing to the volume.

Am I missing something?

**Comment by iYehuda** [comment]
Hello @pepov !

I think you are right.
The check being made is only for existence of `hostPath` volumes of `/var/log`.
We need to check for the `volumeMounts` and filter out read only mounts.

I also spotted another bug in this check - Existence of `hostPath` volumes that are sub-directories under `/var/log` will be reported as well (and are obviously false positives).

We should add some tests while fixing these bugs.

Thanks for reporting!

**Comment by danielsagi** [comment]
@iYehuda @pepov 
You're right, the actual check of the volumeMount is in the ActiveHunter, perhaps its best if we check it as well in the passive one, given that it is already accessible by the /pods data.

About the other issue, subdirectories for /var/log are considered dangerous as well, given that the kubelet serves the entire /var/log directory hierarchy.
