### ISSUE TITLE
interface vboxnet does not exist

### ISSUE THREAD

**Issue by ALuongIBM** [aquasecurity/kube-hunter#184]
Hello,
This is probably a simple question, but when I `python kube-hunter.py` I get the error:
`interface vboxnet does not exist`.
Is this expected?

**Comment by lizrice** [comment]
I think it's a benign warning, but we shouldn't be showing it

**Comment by Frozenaught** [comment]
Hi, if no one is working on this, I would be happy to give it a try.

**Comment by vipulgupta2048** [comment]
@lizrice Simple enough, we can handle this error in the main Python script and write a test for it, so that it doesn't happen again. 
(Also, I am so happy to contribute to Aqua and heard so much about you!! :100: )

**Comment by iYehuda** [comment]
Closing for being stale.
