### ISSUE TITLE
Put on PyPI

### ISSUE THREAD

**Issue by larsrinn** [aquasecurity/kube-hunter#185]
Hi,

great tool, thanks for building it. I'd like to run it from inside a Google Cloud function to regularly scan our clusters. This is rather complicated, if the package can't be installed using pip. Is there any particular reason it is not up on PyPI?

**Comment by lizrice** [comment]
Good idea, we could do that

**Comment by Kerl1310** [comment]
I could pick this up but AFAIK it'd require a PyPi account to be set up?

**Comment by butuzov** [comment]
@Kerl1310 well, you can use test.pypi.org for testing proposes.

**Comment by Kerl1310** [comment]
If so then I'd be happy to work on this

**Comment by vipulgupta2048** [comment]
Hey @Kerl1310, let me know if you are still working on this. I have been working on Python Packaging and would love to apply some skills here. Cheers, 

Steps taken so far, 
- Start preparing Kube-Hunter to be packaged. 
- Created account for test.pypy.org and working on deployment to it per release basis.

**Comment by iYehuda** [comment]
We actually plan to implement packaging and release management soon, although I don't see why not accepting a contribution for this feature if work has already being done.

@Kerl1310 have you made any progress with it?



> Hey @Kerl1310, let me know if you are still working on this. I have been working on Python Packaging and would love to apply some skills here. Cheers,
> 
> Steps taken so far,
> 
> * Start preparing Kube-Hunter to be packaged.
> * Created account for test.pypy.org and working on deployment to it per release basis.

@vipulgupta2048 Sounds like a nice progress.
How do you think to implement release management?
We can use Travis for this task or we can leverage GitHub Actions.
Do you recommend another way of doing so?

**Comment by butuzov** [comment]
Using Travis and condition (tag is present), can help to automate pipy and GitHub releases deployment on the same moment, however, I would go for a manual deployment (as this is a simple twine command).

**Comment by iYehuda** [comment]
I guess using tagged releasing is our go-to

**Comment by vipulgupta2048** [comment]
> We actually plan to implement packaging and release management soon, although I don't see why not accepting a contribution to this feature if work has already being done.

Hello @iYehuda, glad to see an active response. I always wanted to build a deployment pipeline from scratch. So, happy to learn and collaborate on it. Apart, from that, I feel its good contribution nonetheless.

> How do you think to implement release management? We can use Travis for this task or we can leverage GitHub Actions.

I have prior experience with Travis CI, where deployment takes place every release. It works like a charm. That's what we have been using with [Spidermon](https://github.com/scrapinghub/spidermon/blob/master/.travis.yml). Twine looks great too if you like to get deployment done manually. As you have your CI already setup, I think Travis might be a simpler, cleaner option. I am happy with both. We can give Github actions a try as well.

**Comment by iYehuda** [comment]
Would it be reasonable to start implementing manual releases with Twine and migrate to Travis afterwards?

**Comment by vipulgupta2048** [comment]
Perfectly fine with me, I guess by deploying with Twine we can get a level of confidence and reliability that Kube Hunter works fine. From there on, we can proceed to automated deployments. I will get started on that.
