### ISSUE TITLE
pod requires running as root?

### ISSUE THREAD

**Issue by cvernooy23** [aquasecurity/kube-hunter#191]
I have a PSP defined that limits containers/images running as root. kube-hunter, like many images from public registries, fail with the following events:

Successfully assigned default/kube-hunter-tfm68 to <ip_address>
Pulling image "aquasec/kube-hunter"
Successfully pulled image "aquasec/kube-hunter"
Error: container has runAsNonRoot and image will run as root

Name:           kube-hunter-tfm68
Namespace:      default
Priority:       0
Node:           <hostname/ip_address>
Start Time:     Thu, 10 Oct 2019 01:22:47 +0000
Labels:         controller-uid=<UUID>
                job-name=kube-hunter
Annotations:    cni.projectcalico.org/podIP: 10.244.2.135/32
                kubernetes.io/psp: restricted
Status:         Pending
IP:             10.244.2.135
Controlled By:  Job/kube-hunter

by default maybe this shouldn't run as root

**Comment by iYehuda** [comment]
Hi @cvernooy23! sorry about the delay.

Did you try to run kube-hunter with security context of non root user?
As mentioned by @lizrice in #279, the job.yaml spec in this repository is just an example for running kube-hunter and you may change its configuration to fit your needs.

**Comment by iYehuda** [comment]
Closing as being stale.
