### ISSUE TITLE
Translate README.md to PT-BR

### ISSUE THREAD

**Issue by alexaldr** [aquasecurity/kube-hunter#213]
Can I submit a PR translating the README.md to **PT-BR** language? (like _README.pt-BR.md_)

Other users can benefit from this translation.

**Comment by Scorpion136** [comment]
Love it

**Comment by iYehuda** [comment]
Hi @alexaldr !

Referring #216, we decided not to support translations for now.
You may refer to the aforementioned issue for explanation.

Thank you for your proposal.
