### ISSUE TITLE
Translate Readme to Spanish

### ISSUE THREAD

**Issue by parammittal16** [aquasecurity/kube-hunter#216]

**Comment by iYehuda** [comment]
Hi @parammittal16 !

Although it would be helpful to have translation for the project README, it requires every one who wishes to make a change in the README to supply a matching translation to every language we support.
Thinking forward, it will be a liability more than it will contribute.

We would might rethink about translations as the project grows, but for now, the issue will be closed.

Thank you for your proposal.
