### ISSUE TITLE
Profiling is impossible on the script

### ISSUE THREAD

**Issue by RaitoBezarius** [aquasecurity/kube-hunter#234]
## What would you like to be added

Currently, due to the usage of `__main__` to import the `config` object from ArgParse, it is impossible to use external scripts that can instrument the main script (because it changes the entrypoint script).

Making it impossible to use: `cProfile`, `memory_profiler` for instance.

A solution is to create another file `conf.py` and add a global `config` object in it which is initialized from the `kube-hunter.py` script and every other parts of the script can depend on the `conf` module rather than `__main__` (which violates PEP8 BTW).

## Why is this needed

Profiling the script helps developers to debug performance/memory issues, which is critical for a security script.

**Comment by iYehuda** [comment]
Hi @RaitoBezarius !

Good point.
Having config referenced in the main module also limits us with testing.
We can't run pytest directly from command line because of main module imports, hence the `runtest.py`.

Would you like to take this one?

**Comment by RaitoBezarius** [comment]
Hi @iYehuda ! Thank you for your time.
I'd be glad to send a PR for it. :)
