### ISSUE TITLE
Pull Request template needs improving

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/kube-hunter#241]
The PR template doesn't really fit well with this project but the following improvements would make it more worthwhile

* All PRs should reference an issue unless it's a trivial docs change. Say that in a comment and remove "if necessary". Add a tick box to the checklist. 
* Screenshots are rarely the right format in this project, but it would be good to see "before" and "after" terminal output. Change title and remove "if necessary" 
* Add link to Contribution guidelines: https://github.com/aquasecurity/kube-hunter/blob/master/CONTRIBUTING.md
* Remove the tick box about meaningful commit messages, I don't think anyone would read this or go back and change their messages after the event
* Remove the tick box about automated testing, since this is covered in CI/CD anyway
* Add a tick box for "I have added automated testing to cover this case"
* Add a comment asking the submitter to explain if they haven't ticked all the boxes.

**Comment by lizrice** [comment]
@sidhyatikku

**Comment by sidhyatikku** [comment]
@lizrice I would like to get assigned to this issue.

**Comment by iYehuda** [comment]
Resolved by #242
