### ISSUE TITLE
Expose VID on all output types

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/kube-hunter#254]
The VID is currently exposed only for "plain" output (meaning, the terminal output).
We should add it to other types like json/yaml.
Unlike the plain output, where it didn't make sense to add the full url to the report for usability concerns, in the other outputs which are machine readable we should include the url.

(this is also requested for Aqua CSP integration)

**Comment by RaitoBezarius** [comment]
Hi @itaysk 

AFAIK, VID is exposed in JSON/YAML, I can see a `vid` field on `master` version.
But I agree on full URL, I'll send a PR right away if it's okay.

**Comment by RaitoBezarius** [comment]
Well, it's not obvious what would be the full URL because I don't see any hosted docs somewhere, @itaysk — also do we want to hardcode a base URL?

**Comment by itaysk** [comment]
Yes the VID is already there, I didn't notice. Please ignore this issue for now.
