### ISSUE TITLE
Kube-hunter report can't show vulnerabilities online

### ISSUE THREAD

**Issue by hugo320** [aquasecurity/kube-hunter#274]
We can run below command in target machine, and the output report only contains the node information, but can't find the vulnerability report, which shows in the linux box already. Could you please help with this issue?

Command: docker run -it --rm --network host aquasec/kube-hunter --token 
Notes: Token is already included from this command, I just remove it in case sensitive information disclosure.

**Comment by lizrice** [comment]
Hi @hugo320, can you send the output you’re seeing to clarify what the issue is here?

**Comment by iYehuda** [comment]
Closing for being stale.
