### ISSUE TITLE
Kube Hunter Couldn't Find any Clusters

### ISSUE THREAD

**Issue by ZitianXie** [aquasecurity/kube-hunter#284]
Hello, 

I am running kube-hunter in Ubuntu 19.04. I installed the Bookinfo application from Istio using microk8s. However, kube-hunter doesn't seem to find the application inside the cluster.  All kube-hunter found was the main Kubehunter cluster head IP as  10.152.183.1. Kube-hunter did not go inside the cluster to find more vulnerabilities about the application itself.

Here are the running services:

```
***:~/kube-hunter$ microk8s.kubectl get services
NAME             TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
details          ClusterIP      10.152.183.154   <none>        9080/TCP         8d
dvwa-app         LoadBalancer   10.152.183.95    <pending>     80:31740/TCP     58d
dvwasql          NodePort       10.152.183.51    <none>        3306:32438/TCP   58d
kubernetes       ClusterIP      10.152.183.1     <none>        443/TCP          73d
my-service       LoadBalancer   10.152.183.206   <pending>     8080:31340/TCP   43h
my-service-two   NodePort       10.152.183.165   <none>        8080:31784/TCP   43h
productpage      ClusterIP      10.152.183.77    <none>        9080/TCP         8d
ratings          ClusterIP      10.152.183.240   <none>        9080/TCP         8d
reviews          ClusterIP      10.152.183.253   <none>        9080/TCP         8d
```

Here is the result when I tried to use kube-hunter to find vulnerabilities on cluster:
```
***:~/kube-hunter$ python3 kube-hunter.py 
Choose one of the options below:
1. Remote scanning      (scans one or more specific IPs or DNS names)
2. Interface scanning   (scans subnets on all local network interfaces)
3. IP range scanning    (scans a given IP range)
Your choice: 3
CIDR (example - 192.168.1.0/24): 10.152.183.0/24
~ Started
~ Discovering Open Kubernetes Services...
|
| Unrecognized K8s API:
|   type: open service
|   service: Unrecognized K8s API
|_  location: 10.152.183.1:443

----------

Nodes
+-------------+--------------+
| TYPE        | LOCATION     |
+-------------+--------------+
| Node/Master | 10.152.183.1 |
+-------------+--------------+

Detected Services
+----------------------+------------------+----------------------+
| SERVICE              | LOCATION         | DESCRIPTION          |
+----------------------+------------------+----------------------+
| Unrecognized K8s API | 10.152.183.1:443 | A Kubernetes API     |
|                      |                  | service              |
+----------------------+------------------+----------------------+

No vulnerabilities were found

```
Could anyone help me to find out what went wrong? Thanks in advance!

**Comment by iYehuda** [comment]
Hi @ZitianXie !

Correct me if I'm wrong but you expected to see application vulnerabilities as part of kube-hunter report.
kube-hunter does not scan applications that run on top of k8s, but the k8s cluster ecosystem itself (API server, metrics server, etc.)

**Comment by ZitianXie** [comment]
Hello @iYehuda,
Got it, thanks for the reply!

**Comment by ABHISHARMAV** [comment]
I have 2 cluster in gcp, I installed kube-hunter by using docker command. -
$docker run -it --rm --network host aquasec/kube-hunter:aqua --token eyJ0eXAiOiJKV1Qi.....
Choose one of the options below:
1. Remote scanning      (scans one or more specific IPs or DNS names)
2. Interface scanning   (scans subnets on all local network interfaces)
3. IP range scanning    (scans a given IP range)
Your choice: 1
Remotes (separated by a ','): xx.xxx.xx.xyz(node ip)
2020-09-18 10:49:30,458 INFO kube_hunter.modules.report.collector Started hunting
2020-09-18 10:49:30,458 INFO kube_hunter.modules.report.collector Discovering Open Kubernetes Services

Report will be available at:
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| https://kube-hunter.aquasec.com/report.html?token=eyJ0eXAiOiJ |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+


Kube Hunter couldn't find any clusters
2020-09-18 10:49:39,481 INFO root
See full report:
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| https://kube-hunter.aquasec.com/report.html?token=eyJ0eXiOiJKV1Q|


note-I am getting this issue for one cluster node ip's Remote scanning, but another cluster node ip's getting all vulnerability.

help me for this issue
thank you.
