### ISSUE TITLE
Cluster deployed with a Rancher node driver leaves kubelet/etcd ports open according to kube-hunter

### ISSUE THREAD

**Issue by vitobotta** [aquasecurity/kube-hunter#291]
Hi! I am currently using a so called node driver for Rancher to deploy Kubernetes to my cloud provider (Hetzner Cloud), so that Rancher can conveniently manage the nodes for me. This kind of deployment doesn't set up any firewall unfortunately, so while Kube Hunter doesn't report any vulnerabilities, it does report that Kubelet and etcd are open services.

Assuming that unauthenticated access is not permitted to neither kubelet or etcd (I am awaiting a confirmation about this in the Rancher Slack channel), do I need to be worried if the kubelet and especially etcd ports are open?

Thanks in advance!

**Comment by iYehuda** [comment]
Hi @vitobotta, sorry for the delay.

Having no reported vulnerabilities by kube-hunter doesn't necessarily mean that your'e safe.
kube-hunter doesn't cover EVERY vulnerability in the wild, especially ones that aren't reported.
From network security perspective, sensitive services being accessible increases the attack surface and may lead to potential breaches and data leakage.
You can mitigate this by applying network policies to block workloads from accessing those services.

**Comment by vitobotta** [comment]
Hi @iYehuda , in the meantime I have solved by adding some cloud init config to the node template that is used by Rancher to create the servers, so that a firewall is configured, blocking access from the outside world to the API. When I run kube hunter this way it says it cannot find any clusters. Thanks
