### ISSUE TITLE
Add reasonable timeout when discovering kube-apiserver

### ISSUE THREAD

**Issue by invidian** [aquasecurity/kube-hunter#293]
## What would you like to be added

When trying to discover kube-apiserver instances, probe GET requests should have reasonable timeout defined, so `kube-hunter` runs doesn't take a long time.

## Why is this needed

From my limited knowledge and by analyzing debug logs of kube-hunter, I can see, that it tries to get public IP for outgoing traffic of the pod and then tries to scan /24 of this IP address to look for kube-apiserver instances. During this discovery, it tries to make GET requests to kube-apiserver possible ports, here: https://github.com/aquasecurity/kube-hunter/blob/master/kube_hunter/modules/discovery/apiserver.py#L52.

Today when running `kube-hunter`, I hit a server, which takes 5 minutes to timeout responding:
```
130 ✗ (1.270s) 11:29:15 invidian@dellxps15mateusz ~/repos/kinvolk/kube-hunter (master)$ curl -v -s -k https://147.75.32.35:6443
*   Trying 147.75.32.35:6443...
* TCP_NODELAY set
* Connected to 147.75.32.35 (147.75.32.35) port 6443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* Operation timed out after 300495 milliseconds with 0 out of 0 bytes received
* Closing connection 0
28 ✗ (5m0s) 11:34:17 invidian@dellxps15mateusz ~/repos/kinvolk/kube-hunter (master)*$
```

I found this to be an issue while investigating kinvolk/lokomotive-kubernetes#145, where we run `kube-hunter` as part of our CI process.

## Proposed solution

According to https://requests.readthedocs.io/en/master/user/advanced/#timeouts, timeout can be easily added to https://github.com/aquasecurity/kube-hunter/blob/master/kube_hunter/modules/discovery/apiserver.py#L52.

In my opinion 30 seconds should be more than enough to connect + receive some data from `kube-apiserver`. Perhaps the lower value, the better.

**Comment by iYehuda** [comment]
Hi @invidian !

Thanks for raising an issue.
I agree about setting a timeout, it's a good practice and improves scanning time.
Can you supply some information about your environment in order to reproduce that?

**Comment by invidian** [comment]
Hi @iYehuda, thanks for follow up. I'm the maintainer of https://github.com/kinvolk/lokomotive-kubernetes and we run `kube-hunter` as part of our CI process. We had some [issues](https://github.com/kinvolk/lokomotive-kubernetes/issues/145), that sometimes kube-hunter scanning was timing out, which was causing CI to fail.

It was happening on [Packet](https://www.packet.com/) platform, so you can follow [this](https://github.com/kinvolk/lokomotive-kubernetes/blob/master/docs/flatcar-linux/packet.md) guide to setup the environment, where it can be reproduced. Please note, that reproducibility depends on what public IP you get. Let me know if you have some questions.

**Comment by iYehuda** [comment]
I managed to reproduce this issue by blocking HTTP using network policy.
This way kube-hunter discovers a host using ping, tries to probe an api endpoint it via HTTP and blocks.

**Comment by iYehuda** [comment]
Thanks a lot @invidian!

You helped us figuring out an old [forgotten issue](#35).
I'm closing this in favor of that issue.
