### ISSUE TITLE
Standard build with PyInstaller

### ISSUE THREAD

**Issue by iYehuda** [aquasecurity/kube-hunter#301]
## What would you like to be added
Add support for PyInstaller build.
That is not trivial since there are dynamic imports in kube-hunter code base, which should be treated individually when building \w PyInstaller.

## Why is this needed
There are kinds of integrations which cannot have python exists.
We can use PyInstaller to "freeze" kube-hunter to a single executable binary.
Going further we can use tools such as [staticx](https://github.com/JonathonReinhart/staticx) to generate a standalone statically linked binary, thus being portable to non glibc environments. 

Related to #290

**Comment by itaysk** [comment]
why do we need pyinstaller, when we already distribute kube-hunter as a docker image?

**Comment by iYehuda** [comment]
There are integrations such as Aqua CSP which embed kube-hunter inside a non python based docker image. Installing python makes the image bigger so they use PyInstaller to bundle kube-hunter as a single binary.
