### ISSUE TITLE
Link to EULA for Docker containers

### ISSUE THREAD

**Issue by ramshazar** [aquasecurity/kube-hunter#31]
Hi,

if you really want to use uploaded reports from the docker container version it may be a good idea to link to the EULA in the readme of this repository.

Link: https://kube-hunter.aquasec.com/eula.html

> Customer hereby agrees that Aqua may upload samples of such results to its servers for its internal informational and research purposes

Kind regards,
Matthias

**Comment by lizrice** [comment]
Good idea, thank you @ramshazar
