### ISSUE TITLE
Fail to generate json/yaml report. Command line option not working

### ISSUE THREAD

**Issue by tempandk123** [aquasecurity/kube-hunter#312]
### What happened

Following the last commit, when I run kube-hunter.py I cannot get the json (nor yaml) report anymore. The "--report" option does not seem to be working.

![image](https://user-images.githubusercontent.com/61027695/75364116-2d2e6300-5889-11ea-940d-68e0ec33123a.png)

### Expected behavior

I should get the report in a JSON format.

**Comment by iYehuda** [comment]
Hi @tempandk123 !

Thanks for your report.
I have verified this in it looks like #310 created a regression.

@mormamn It looks like the factory implementation did not instantiated reporters and dispatchers.
This part should be tested.

**Comment by mormamn** [comment]
@iYehuda , I apologize it's my bad for not testing.
Anyway, I'll make sure it wont happen again.
I'm on it, + test file.
