### ISSUE TITLE
Log output redirection

### ISSUE THREAD

**Issue by iYehuda** [aquasecurity/kube-hunter#329]
## What would you like to be added
Enable separation of report and log into two separate destinations.
Supply a configurable log output file.

## Why is this needed
In order to make kube-hunter automation and human friendly, we should enable separation of logs and reports in a convenient way.
Right now, log messages are being printed to the standard error and the report is written into the standard output.
If you want to separate them apart, you'll need to use shell redirection (e.g., `2> kube-hunter.log`).
We can save the user from using shell output redirection and supply a parameter for log file path (`--log-file`).

**Comment by jabhishek87** [comment]
can i take this ?

**Comment by Nibba2018** [comment]
Is this issue still open @iYehuda ?

**Comment by milindchawre** [comment]
assign @milindchawre
