### ISSUE TITLE
missing --internal option

### ISSUE THREAD

**Issue by Eremiel** [aquasecurity/kube-hunter#343]
### What happened
When running kube-hunter from pod I am getting message:
Kube Hunter couldn't find any clusters

found a solution to replace --pod arg with --internal https://github.com/aquasecurity/kube-hunter/issues/44
But this results in error:
kube-hunter.py: error: unrecognized arguments: --internal

was this option abandoned?

### Expected behavior
Kube hunter finds the cluster properly

**Comment by iYehuda** [comment]
Hi @Eremiel 

The flag `--internal` was renamed to `--interface` 7 months ago by [this commit](https://github.com/aquasecurity/kube-hunter/commit/44e6438d37fd6e2c8a1bfbf02b145003aef309d6)
Please refer to the [README](https://github.com/aquasecurity/kube-hunter/blob/master/README.md#scanning-options) for information about scanning options.
