### ISSUE TITLE
kube-hunter: error: unrecognized arguments: --token 

### ISSUE THREAD

**Issue by aldavidov** [aquasecurity/kube-hunter#345]
Hi,

I'm trying to run kube-hunter after getting the command from here:https://kube-hunter.aquasec.com/

I'm getting and Error:
kube-hunter: error: unrecognized arguments: --token eyJ0eXAiOiJKV1QiLCJhbGciO

I managed to run the application locally.
Please advise.

**Comment by brondum** [comment]
Same here! 
If i then use the :aqua tag from the registry it runs, but the report does not show at the web interface.
It just stops loading.

**Comment by danielsagi** [comment]
@aldavidov @brondum 
Hi, The issue was now solved and the flow of the site UI scan is working, Try it!
Currently we are working on a new design, so stay tuned :)
