### ISSUE TITLE
Final hook is hanging

### ISSUE THREAD

**Issue by rtoma** [aquasecurity/kube-hunter#35]
Hi,

Thanks for the tool!

When running aquasec/kube-hunter with `--pod` and `--log=info` inside of a GKE cluster  I get this output:

```
...
~ Started
~ Discovering Open Kubernetes Services...
Event <class 'src.modules.discovery.hosts.HostScanEvent'> got published with <src.modules.discovery.hosts.HostScanEvent object at 0x7fc91436ced0>
Starting new HTTP connection (1): 169.254.169.254:80
http://169.254.169.254:80 "GET /metadata/instance?api-version=2017-08-01 HTTP/1.1" 403 56
Starting new HTTP connection (1): canhazip.com:80
http://canhazip.com:80 "GET / HTTP/1.1" 200 14
Starting new HTTP connection (1): www.azurespeed.com:80
http://www.azurespeed.com:80 "GET /api/region?ipOrUrl=x.x.x.x%0A HTTP/1.1" 200 None
Cannot read wireshark manuf database
```

It eventually stops with `Kube Hunter couldn't find any clusters` (\o/ us), but I am wondering what if the manuf db was available for scapy (?). Maybe something to look into.

**Comment by lizrice** [comment]
This is a benign warning issued by scapy and doesn't affect the behaviour of kube-hunter, but it would be better if we could find a way for it to be avoided.

**Comment by Joeyn414** [comment]
I dont get that much output I'm currently only seeing this:
`~ Started
~ Discovering Open Kubernetes Services...
Cannot read wireshark manuf database`

I did not modify the job.yaml file at all when running it as a job in kubernetes. It just sits there and doesnt do anything else. You state its a benign error but it doesnt move on past this. What can I do to fix whatever is wrong with my setup?

**Comment by JPLachance** [comment]
Hello,

I just tried to deploy the latest version of the kube-hunter job in an AWS EKS cluster and I'm seeing the same behavior described here. In the pod logs, I see:
```
~ Started
~ Discovering Open Kubernetes Services...
Cannot read wireshark manuf database
```
Then nothing else happens.

I tried to deploy the same job in a Kubernetes cluster deployed by KOPS and it worked perfectly.

Maybe GKE and EKS are blocking kube-hunter?

**Comment by lizrice** [comment]
Thank you @JPLachance, we will check that out, it's a good thought. My immediate thought is wondering if it's something to do with security groups that don't allow traffic on these ports. 

@joeyn414 @rtoma what are your environments?  I think the log itself is a red herring but that the idea that something blocks kube-hunter is very plausible.

**Comment by Joeyn414** [comment]
I'm running it in EKS.

**Comment by ImPurshu** [comment]
~ Started
~ Discovering Open Kubernetes Services...
|
| Accessed to pod's secrets:
|   type: vulnerability
|   host: None:None
|   description:
|     Accessing the pod's secrets within a
|     compromised pod might disclose valuable data to a
|_    potential attacker
Cannot read wireshark manuf database
 
Same error I am facing on EKS.
Any idea?

**Comment by aakarshit-batchu** [comment]
Hi,
Facing the same issue with kube-hunter pod.

~ Started
~ Discovering Open Kubernetes Services...
|
| Read access to pod's service account token:
|   type: vulnerability
|   host: None:None
|   description:
|     Accessing the pod service account token
|     gives an attacker the option to use the
|_    server API
|
| Access to pod's secrets:
|   type: vulnerability
|   host: None:None
|   description:
|     Accessing the pod's secrets within a
|     compromised pod might disclose valuable data to a
|_    potential attacker
Cannot read wireshark manuf database

Kube Hunter couldn't find any clusters


Kindly help me with this issue.

**Comment by dylancaponi** [comment]
Same issue on EKS after running `kubectl create pod.yaml`

```
~ Started
~ Discovering Open Kubernetes Services...
|
| Accessed to pod's secrets:
|   type: vulnerability
|   host: None:None
|   description:
|     Accessing the pod's secrets within a
|     compromised pod might disclose valuable data to a
|_    potential attacker
Cannot read wireshark manuf database
```

**Comment by aryak93** [comment]
Any update on this? We are also facing the same issue.

**Comment by gramidt** [comment]
> Any update on this? We are also facing the same issue while running on `EKS`

@aryak93 @dylancaponi - I will setup an EKS cluster this week and see if I can reproduce what you are both seeing.

**Comment by denniswebb** [comment]
@gramidt Any luck? I'm having the same issue on a fresh EKS cluster.

**Comment by denniswebb** [comment]
I did some more testing. Running an image from `master`, then truncated results are
```Starting new HTTP connection (1): 169.254.169.254:80
Event <class 'src.modules.hunting.secrets.SecretsAccess'> got published with <src.modules.hunting.secrets.SecretsAccess object at 0x7fd4c1b4d390>
|
| Access to pod's secrets:
|   type: vulnerability
|   location: Local to Pod(kube-hunter-glm9l)
|   description:
|     Accessing the pod's secrets within a
|     compromised pod might disclose valuable data to a
|_    potential attacker
http://169.254.169.254:80 "GET /metadata/instance?api-version=2017-08-01 HTTP/1.1" 404 345
Starting new HTTP connection (1): canhazip.com:80
http://canhazip.com:80 "GET / HTTP/1.1" 200 12
Checking whether the cluster is deployed on azure's cloud
Starting new HTTPS connection (1): www.azurespeed.com:443
https://www.azurespeed.com:443 "GET /api/region?ipOrUrl=64.57.9.147%0A HTTP/1.1" 200 None
1 tasks left
final hook is hanging
1 tasks left
final hook is hanging```

**Comment by danielsagi** [comment]
@denniswebb Hi dennis, this issue could be related to a raw_socket opening. 
could you run this in a python shell and send the output?
```python
from scapy.all import ICMP, IP, Ether, srp1
srp1(Ether() / IP(dst="google.com" , ttl=1) / ICMP())[IP].src
```

**Comment by Spareo** [comment]
I just tried deploying this to EKS and have the exact same issue.

**Comment by Spareo** [comment]
@danielsagi I just ran that on my EKS cluster. I exec'd into the Kube-hunter pod and just started a python shell and ran those statements....

```
Type "help", "copyright", "credits" or "license" for more information.
>>> from scapy.all import ICMP, IP, Ether, srp1
>>> srp1(Ether() / IP(dst="google.com" , ttl=1) / ICMP())[IP].src
Begin emission:
.Finished sending 1 packets.
```

It just hangs after that and never returns anything. We have egress rules on our node security groups that might be blocking this, although we do allow traffic out on 80 and 443 as well as some other necessary ports.

**Comment by lizrice** [comment]
Renamed issue to better reflect what it's currently tracking

**Comment by RaitoBezarius** [comment]
According to this https://github.com/secdev/scapy/issues/621 it could be related to not choosing the interface, maybe as `netifaces` is already used in the Discovery Host module, it can be reused for the DNS/ARP module to choose a canonical interface and avoid routing issues.
I can send a PR but unsure if I can reproduce the bug.

**Comment by iYehuda** [comment]
This issue looks a lot like #293. 
The source of this bug is operations being made without timeout (HTTP requests and scapy packet sending).
