### ISSUE TITLE
Docker container Kube-hunter --token issue command

### ISSUE THREAD

**Issue by MSidda** [aquasecurity/kube-hunter#356]
while running this command getting following error, i need to check vulnerabilities of my nodes on dashboard

docker run -it --rm --network host aquasec/kube-hunter --token <token>
kube-hunter: error: unrecognized arguments: --token

please help me

**Comment by danielsagi** [comment]
Hi, 
Currently kube-hunter.aquasec.com reports feature is down, we are working to fix this problem.
Please check in on the following pr #357
This problem is supposed to be fixed when this PR is approved.
