### ISSUE TITLE
Readme doc update

### ISSUE THREAD

**Issue by Surajv311** [aquasecurity/kube-hunter#379]
## What would you like to be added

I would like to add the **License** section in the **Table of Contents** in the README.md file.

## Why is this needed

It has been added in a few other repos hence I believe it can be implemented in this repo as well.

@itaysk

**Comment by itaysk** [comment]
Hello and thanks for opening an issue. While we do welcome improvements to the readme, the intention was to better document the usage and technical aspects of the project, rather than logistics or legal. We already have the license badge which is sufficient in this case.

**Comment by Surajv311** [comment]
Okay @itaysk 👍
