### ISSUE TITLE
kube-hunter throwing python library error during installation 

### ISSUE THREAD

**Issue by n1shant-sinha** [aquasecurity/kube-hunter#435]
## Kube-Hunter installation issue on Python 2.7 and 3.8.3. 

it is showing me the following error each time I am trying to install the tool. 

![image](https://user-images.githubusercontent.com/8848453/105082964-4b352100-5a62-11eb-8dc0-f18dab099f33.png)

**Comment by danielsagi** [comment]
This was fixed for a while now :)
Closing
