### ISSUE TITLE
Kube Hunter couldn't find any clusters for openshift worker nodes

### ISSUE THREAD

**Issue by aayu-gehlod** [aquasecurity/kube-hunter#438]
While running kube-hunter --remote for master-nodes a report is generated but getting "Kube Hunter couldn't find any clusters" when giving worker-nodes-ip
 
kube-hunter --remote worker-node-ip 
output: kube Hunter couldn't find any clusters

**Comment by danielsagi** [comment]
While kube-hunter is not directly built for Openshift, it will sometimes work. You can try to run it inside the cluster and see if there's a change in the output.
But we don't officially support openshift at this moment...
