### ISSUE TITLE
When should  kube-hunter be run in active mode

### ISSUE THREAD

**Issue by k-p-ani** [aquasecurity/kube-hunter#440]
Hello everyone,
 Has anyone used kube-hunter in active mode ? Ideally when should we use active mode and how frequent we should run? Should we create a new Kubernetes cluster which is identical to production cluster and with same work load and then run kube-hunter in active mode against this new production like Kubernetes cluster to find vulnerabilities ?

**Comment by danielsagi** [comment]
Hi @k-p-ani 
I didn't see you there.
Active hunting just means that kube-hunter can do active actions against the cluster. creating pods for example. this does mean that it will generally produce more output.
If you don't want this behavior in your production cluster you should run it in passive mode.
