### ISSUE TITLE
GKE and EKS tests for metadata API access

### ISSUE THREAD

**Issue by lizrice** [aquasecurity/kube-hunter#45]
We have a hunter for metadata acces on Azure, we should add the equivalents for Google and AWS

**Comment by gramidt** [comment]
@lizrice I would love to create the corresponding hunters for GCP and AWS! I will likely start with the AWS then move onto GCP. Any thoughts or recommendations you have before I get started?

**Comment by lizrice** [comment]
That would be great! Thank you @gramidt. I don’t have any particular thoughts other than the docs for these metadata services: 
- [EC2 metata](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html) looks straightfoward.  
- On GCP the [advice for protecting metadata](https://cloud.google.com/kubernetes-engine/docs/how-to/protecting-cluster-metadata) includes info on some legacy endpoints we might want to hunt for as well as the current ones

**Comment by gramidt** [comment]
Thanks, @lizrice! I'll work on EC2 metadata this weekend. 

Super excited to start contributing to both kube-hunter and kube-bench. Two projects I absolutely love!

**Comment by gramidt** [comment]
I apologize for the delay, @lizrice! I have allocated time this week to work on this. 

I will let you know if I have any questions.

**Comment by haileymothershead** [comment]
@lizrice is this issue open to contributions? I'm currently a senior at UT Austin and am taking a virtualization class. As part of the class we're supposed to work on an open source project and we'd love to handle this issue!

**Comment by itaysk** [comment]
@haileymothershead feel free to work on this (or other issues that you like)

**Comment by gramidt** [comment]
@lizrice @itaysk - I apologize for slacking and forgetting about this. I just started it last night and will be wrapping up the AWS EC2 Metadata API check today. Currently, I am on extending the data retrieved for the vulnerability event. Similar to the Azure Metadata API, the AWS Metadata API contains networking details, but also a bunch of other data points as well, including IAM secrets.

**Comment by jan0ski** [comment]
This issue looks quite stale, is someone still working on this?  I'll pick this up if nobody minds.
