### ISSUE TITLE
Use of scapy and possible Apache-GPL license conflict

### ISSUE THREAD

**Issue by pegasusgh** [aquasecurity/kube-hunter#494]
kube-hunter is licensed under Apache 2.0.  kube-hunter includes scapy.  scapy is licensed under GPL 2.0.  According to https://www.apache.org/licenses/GPL-compatibility.html, there is a license conflict.  How does the kube-hunter project work around/through this?

**Comment by danielsagi** [comment]
Hi @pegasusgh . Thanks for raising this issue! kube-hunter did not work around the license conflict. but we are moving the problematic code under a new project.

**Comment by pegasusgh** [comment]
Thank you for the confirmation, @danielsagi .  Is there a timeframe for moving the code licensed under GPL?  Does the project exist so that it can be followed by those interested?
