### ISSUE TITLE
Pinned image not updated nor set correctly in docker hub

### ISSUE THREAD

**Issue by rhtenhove** [aquasecurity/kube-hunter#507]
### What happened

After merging #504, nothing seemed to happen what was expected.

### Expected behavior

- The new image on Docker Hub would be tagged `v0.6.8`
- The job manifest tag would be updated with `v0.6.8` as well.

### Actual behaviour

- A new image with tag `0.6.8` was pushed to Docker hub
- The job manifest is still at v0.6.7

Now the manifest won't work at all.

### Needed changes

1. I'll create an MR to make the `publish.yaml` GA the same as for `kube-bench`. Can someone check if that will do as expected? `kube-bench` uses `workflow_dispatch:` so perhaps there's some manual step going on there that adds the `v`?
2. Do you use semver to make automated changes in the repo to update version numbers anywhere? I'm not sure how they do it for `kube-bench`, perhaps manually every time?

To 'fix' 1., we could also use the image tag without the `v` and update that in the manifest. In the end it's just OCD that wants things to be the same.

**Comment by rhtenhove** [comment]
Just read in the documentation of `crazy-max/ghaction-docker-meta@v3` that we're supposed to use `{{raw}}` instead of `{{version}}`, although `kube-bench` doesn't do that either.

Hopefully someone working on both projects can elaborate :)

**Comment by danielsagi** [comment]
Hi, the v0.6.8 came out before this PR was merged. meaning the action didnt run.
Further releases should be affected though.
