### ISSUE TITLE
netifaces needs a maintainer

### ISSUE THREAD

**Issue by 06kellyjac** [aquasecurity/kube-hunter#516]
### What happened

Since 2021-05-31 netifaces has been marked as needing a maintainer and at some point since then the repo has been marked as archived

kube-hunter might need to move to a different library or maintain netifaces

ifaddr has what seems to be a small subset of the functionality but can't grab the "default" interface

https://github.com/pydron/ifaddr/issues/41

**Comment by newtondev** [comment]
Hi @06kellyjac 

Another nice network library to try out is pyroute2: https://github.com/svinota/pyroute2

```
from pyroute2 import IPDB
ip = IPDB()
# interface index:
print(ip.routes['default']['oif'])
# interface details:
print(ip.interfaces[ip.routes['default']['oif']])
# release DB
ip.release()
```
