### ISSUE TITLE
With release: "error while loading shared libraries: libz.so.1: failed to map segment from shared object"

### ISSUE THREAD

**Issue by cosad3s** [aquasecurity/kube-hunter#522]
### What happened

I downloaded the last release of kube-hunter: https://github.com/aquasecurity/kube-hunter/releases/tag/v0.6.8.

On launching on my remote machine, I get the error: `./kube-hunter: error while loading shared libraries: libz.so.1: failed to map segment from shared object`

### Expected behavior

Successfull launch.

### Notes

- Python version: 3.6.8
- Machine not connected to Internet
- Red Hat Enterprise Linux release 8.4 - Linux version 4.18.0-372.13.1.el8_6.x86_64

**Comment by newtondev** [comment]
To resolve this issue, please try one of the following two available methods. 

Remount /TMP with exec permissions using this command:
`sudo mount /tmp -o remount,exec`

OR

Set the TMP directory to a different directory where you can add exec permissions:
`TMP=/home/<username>/<directory>`

OR 

`sudo mount /tmp -o remount,exec`
Put `export TMPDIR=$HOME/tmp` on the `~/.bashrc` file
