### ISSUE TITLE
Kube Hunter couldn't find any clusters

### ISSUE THREAD

**Issue by lmeyemezu** [aquasecurity/kube-hunter#61]
Hi,
trying to launch ./kube-hunter.py --active on k8s installed on-prem with kubeadm.
got 
|
| API Server:
|   type: open service
|   service: API Server
|_  host: 198.18.240.90:443
Passive hunter is attempting to get server certificate
|
| API Server:
|   type: open service
|   service: API Server
|_  host: 198.18.240.86:443
Incorrect padding
Reachable port found: 443
Event <class 'src.core.events.types.common.OpenPortEvent'> got published with 443
Incorrect padding
Incorrect padding
Incorrect padding
Incorrect padding
Incorrect padding
Incorrect padding
Incorrect padding
Incorrect padding
Incorrect padding
Incorrect padding
Incorrect padding
Attempting to discover an Api server
Incorrect padding
Incorrect padding
Incorrect padding
Starting new HTTPS connection (1): 198.18.240.247:443
https://198.18.240.247:443 "GET / HTTP/1.1" 403 185
Event <class 'src.modules.discovery.apiserver.ApiServer'> got published with <src.modules.discovery.apiserver.ApiServer object at 0x7f9b606d2d90>
|
| API Server:
|   type: open service
|   service: API Server
|_  host: 198.18.240.247:443
Passive hunter is attempting to get server certificate
https://198.18.240.212:10250 "GET /pods HTTP/1.1" 401 12
Starting new HTTPS connection (1): 198.18.240.212:10250
https://198.18.240.212:10250 "GET /healthz HTTP/1.1" 401 12
https://198.18.240.215:10250 "GET /pods HTTP/1.1" 401 12
Starting new HTTPS connection (1): 198.18.240.215:10250
https://198.18.240.213:10250 "GET /pods HTTP/1.1" 401 12
Starting new HTTPS connection (1): 198.18.240.213:10250
https://198.18.240.214:10250 "GET /pods HTTP/1.1" 401 12
Starting new HTTPS connection (1): 198.18.240.214:10250
https://198.18.240.215:10250 "GET /healthz HTTP/1.1" 401 12
https://198.18.240.213:10250 "GET /healthz HTTP/1.1" 401 12
https://198.18.240.214:10250 "GET /healthz HTTP/1.1" 401 12
https://172.17.0.1:10250 "GET /pods HTTP/1.1" 401 12
Starting new HTTPS connection (1): 172.17.0.1:10250
https://172.17.0.1:10250 "GET /healthz HTTP/1.1" 401 12
Event <class 'src.core.events.types.common.HuntFinished'> got published with <src.core.events.types.common.HuntFinished object at 0x7f9b8406ec10>

Kube Hunter couldn't find any clusters

----------

Event <class 'src.modules.report.collector.TablesPrinted'> got published with <src.modules.report.collector.TablesPrinted object at 0x7f9b8406e3d0>
Cleaned Queue

**Comment by lizrice** [comment]
Thanks for raising. Just noting that the incorrect padding error may well come from base64 decoding. Needs investigation

**Comment by lmeyemezu** [comment]
Hi @lizrice 
Any update ?
Regards

**Comment by hypery2k** [comment]
experencing the same error. sometimes getting the same error, but only in same cases. In most of the run it just works

**Comment by davidkarlsen** [comment]
no paddng problem - but can't find any cluster here either:
```
~ Started
~ Discovering Open Kubernetes Services...
|
| Accessed to pod's secrets:
|   type: vulnerability
|   host: None:None
|   description: 
|     Accessing the pod's secrets within a
|     compromised pod might disclose valuable data to a
|_    potential attacker

----------


Kube Hunter couldn't find any clusters
```

Using this chart: https://github.com/helm/charts/tree/master/stable/kube-hunter

**Comment by ImPurshu** [comment]
~ Started
~ Discovering Open Kubernetes Services...
|
| Accessed to pod's secrets:
|   type: vulnerability
|   host: None:None
|   description:
|     Accessing the pod's secrets within a
|     compromised pod might disclose valuable data to a
|_    potential attacker
Cannot read wireshark manuf database

Same error I am facing.
Any idea?

**Comment by jayunit100** [comment]
same here, `kubectl create -f job.yml`, then the logs:

```
~ Started
~ Discovering Open Kubernetes Services...
|
| Accessed to pod's secrets:
|   type: vulnerability
|   host: None:None
|   description:
|     Accessing the pod's secrets within a
|     compromised pod might disclose valuable data to a
|_    potential attacker
----------
Kube Hunter couldn't find any clusters
```

**Comment by aakarshit-batchu** [comment]
Hi Guys,
Facing the same issue here with kube-hunter pod batch job.

`~ Started
~ Discovering Open Kubernetes Services...
|
| Read access to pod's service account token:
|   type: vulnerability
|   host: None:None
|   description:
|     Accessing the pod service account token
|     gives an attacker the option to use the
|_    server API
|
| Access to pod's secrets:
|   type: vulnerability
|   host: None:None
|   description:
|     Accessing the pod's secrets within a
|     compromised pod might disclose valuable data to a
|_    potential attacker
Cannot read wireshark manuf database

Kube Hunter couldn't find any clusters
`

Kindly help me with this issue.

**Comment by Richahasija** [comment]
i Guys,
Facing the same issue here with kube-hunter remote scanning 

~ Started
~ Discovering Open Kubernetes Services...

Kube Hunter couldn't find any clusters

----------

**Comment by jgsqware** [comment]
What is the correct format kube-hunter is expecting?

**Comment by anjaligau** [comment]
Any update on this bug , i want to run kube hunter in my cluster.

**Comment by sachsachdeva** [comment]
Facing the same Issue, I tried this on the AKS cluster today

~ Started
~ Discovering Open Kubernetes Services...
|
| Accessed to pod's secrets:
|   type: vulnerability
|   host: None:None
|   description:
|     Accessing the pod's secrets within a
|     compromised pod might disclose valuable data to a
|_    potential attacker

----------

**Comment by davidkarlsen** [comment]
Is this project dead?

**Comment by lizrice** [comment]
Far from it! Note that not being able to find any clusters is a perfectly plausible response - for example if the cluster is not accessible over the network from where kube-hunter is run. 

Please run with logging turned on @sachsachdeva so we can get some clues. Also @danielsagi to re-test on AKS when you have a chance.

**Comment by danielsagi** [comment]
@sachsachdeva @aakarshit-batchu @davidkarlsen please see #140.
This fixes the issue in your case of not printing the vulnerabilities found from running with job.yaml.

@lmeyemezu After: #137 exceptions are now logged correctly, so if you would run now, we can debug and see the origin of the "incorrect padding" error you got, also, there has been multiple PR's from when this issue was posted, so theres a good chance it was fixed.
if the problem consists in reproduction, please open a new issue, with the output of the debug messages of "incorrect padding"
