### ISSUE TITLE
Show vulnerability id

### ISSUE THREAD

**Issue by hypery2k** [aquasecurity/kube-hunter#64]
is it possible to show the concrete CVE record, e.g

**Comment by lizrice** [comment]
I don't think all vulnerabilities will have a CVE (for example, if you configure Kubernetes with anonymous access and RBAC wide open, the cluster is vulnerable to attack but not because of a software vulnerability. But I agree we should report CVE numbers where they are available.

**Comment by lizrice** [comment]
We do now show CVE numbers for specific CVE vulnerabiltiies
