### ISSUE TITLE
Vulnerabilities not shown in dashboard

### ISSUE THREAD

**Issue by kiranp227** [aquasecurity/kube-hunter#70]
@![screen shot 2018-12-13 at 11 49 15 am](https://user-images.githubusercontent.com/20418164/49921296-1f363180-fed3-11e8-8575-c5d1c1dee344.png)

When I scan with kube-hunter, It is identifying some vulnerabilities. But the vulnerabilities are not shown in the dashboard. 

![screen shot 2018-12-13 at 12 35 53 pm](https://user-images.githubusercontent.com/20418164/49921507-b69b8480-fed3-11e8-9f89-a965e893af00.png)

Please let me know what could be possible issue.

**Comment by oriagmon** [comment]
Hey, thank you for opening the issue.

The problem applies only to the new CVE Hunter, We are already aware of
that, and hope to handle it soon.

**Comment by lizrice** [comment]
@danielsagi is this now fixed?
