### ISSUE TITLE
Have a toggle to make logs machine readable

### ISSUE THREAD

**Issue by swade1987** [aquasecurity/kube-hunter#78]
Have an environment or argument to allow logs to be printed to STDOUT in machine-readable format. This makes ingesting job output into Elasticsearch or other log aggregators

**Comment by lizrice** [comment]
@swade1987 does #92 give you what you need for this?

**Comment by swade1987** [comment]
@lizrice looks good does @maniish-jaiin have an output to view?

**Comment by maniish-jaiin** [comment]
<img width="670" alt="screenshot 2019-02-21 at 13 22 27" src="https://user-images.githubusercontent.com/19270238/53168785-c32b1000-35db-11e9-99cb-84df486d6a08.png">

**Comment by maniish-jaiin** [comment]
The data is confidential and I can share with you the output for the same. But its verifies and it outputs one liner json.

**Comment by swade1987** [comment]
So would the output to STDOUT by one massive JSON blob?

**Comment by maniish-jaiin** [comment]
Yes!

**Comment by maniish-jaiin** [comment]
Its tested with the Datadog ingest and it works fine there, as the plain text and the yaml can't be consumed by the Datadog, and I guess that would be the case with the other platforms as well.

**Comment by swade1987** [comment]
We will be consuming via Fluentbit into Elasticsearch.

**Comment by lizrice** [comment]
@swade1987 I'll close this now, but please do re-open if you don't have what you need
